/*
 * proc.h — processes, scheduling and signals. (GPLv2)
 *
 * A process owns an address space, a kernel stack, a file-descriptor table
 * and a place in a process group.  Process groups are what make job control
 * possible: the tty remembers one "foreground" group, signals generated by
 * the keyboard go to every member of it, and everyone else is either running
 * quietly in the background or stopped.
 */
#ifndef GNUCOS_PROC_H
#define GNUCOS_PROC_H

#include <stdint.h>

#include "vmm.h"
#include "panic.h"

#define MAX_PROCS     16
#define KSTACK_SIZE   0x4000        /* 16 KiB */

/* A full libc program opens far more descriptors than the toy utilities did:
 * BusyBox's `cp -a` alone holds a source fd, a destination fd and a directory
 * fd per recursion level, and musl keeps stdio buffers on top.  64 is cheap
 * (an int each) and removes the ceiling as a thing to think about. */
#define PROC_MAX_FD   64

/* Process states.  STOPPED is distinct from BLOCKED: a stopped process is
 * not waiting for anything, it has been suspended by a job-control signal
 * and only SIGCONT will bring it back. */
typedef enum {
    PROC_UNUSED = 0,
    PROC_READY,
    PROC_RUNNING,
    PROC_BLOCKED,
    PROC_STOPPED,
    PROC_ZOMBIE,
} proc_state_t;

/* Why a BLOCKED process is blocked. */
typedef enum {
    WAIT_NONE = 0,
    WAIT_CHILD,
    WAIT_TTY,
    WAIT_PIPE,
    WAIT_NET,
} wait_reason_t;

/* Signal numbers, wait() flags and the rest of the user-visible constants
 * come from the shared contract header, so the kernel cannot disagree with
 * the programs it runs. */
#include "sysnum.h"

/* 64 rather than 32 because that is the width musl talks in: every
 * rt_sigprocmask/rt_sigaction it issues carries sigsetsize == 8. */
#define NSIG    64

/* Linux/musl put signal N at bit (N-1) of a sigset, so SIGUSR1 (10) is bit
 * 9 and SIGUSR2 (12) is bit 11.  Matching that convention end-to-end is what
 * lets a sigset the libc fills in and the one the kernel masks on actually
 * refer to the same signal. */
#define SIGMASK(n) (1ull << ((uint64_t)(n) - 1))

/* One disposition, in the shape the kernel/user rt_sigaction ABI uses.  Note
 * this is the *kernel's* 32-byte struct sigaction, not the 152-byte one in
 * <signal.h>; musl translates between the two. */
typedef struct {
    uint64_t handler;           /* SIG_DFL, SIG_IGN, or a user address */
    uint64_t flags;             /* SA_* */
    uint64_t restorer;          /* required when handler is a real address */
    uint64_t mask;              /* extra signals blocked during the handler */
} sigact_t;

typedef struct proc {
    int           pid;
    int           ppid;
    int           pgid;             /* process group: the unit of job control */
    proc_state_t  state;
    wait_reason_t wait_reason;
    int           wait_pid;         /* which child waitpid() is after, -1 = any */
    uint64_t      wake_tick;        /* timer tick to wake at, 0 = no deadline */

    /* ITIMER_REAL, in scheduler ticks.  It counts wall-clock time, so unlike
     * wake_tick it keeps running while the process is descheduled -- which is
     * the point of alarm(): interrupting a call that is stuck. */
    uint64_t      itimer_expire;    /* tick to raise SIGALRM at, 0 = off */
    uint64_t      itimer_interval;  /* re-arm period in ticks, 0 = one-shot */

    addrspace_t  *as;
    uint64_t      kstack_top;
    uint64_t      saved_rsp;        /* where switch_context parked this task */

    int           fds[PROC_MAX_FD]; /* -1, or a handle into the open-file table */

    uint64_t      sig_pending;
    uint64_t      sig_ignored;
    uint64_t      sig_mask;         /* signals blocked from delivery */
    sigact_t      sigact[NSIG];     /* installed dispositions */

    /* The syscall number the current trap came in with, or -1 when the trap
     * is not a restartable syscall.  syscall_handler() overwrites RAX with
     * the result before anyone gets to look at signals, so SA_RESTART needs
     * its own copy to rewind to. */
    int64_t       syscall_nr;

    uint64_t      brk;              /* current data break (sbrk/brk) */
    uint64_t      fs_base;          /* TLS base (arch_prctl ARCH_SET_FS) */
    uint64_t      clear_child_tid;  /* set_tid_address: futex word to clear */

    /* Anonymous mappings we handed out, so munmap()/exit can free them.
     * musl's malloc grabs a fresh mmap for each heap "group", so a busy
     * process (or a full libc program like BusyBox) can hold far more than a
     * handful; 128 keeps the per-PCB bookkeeping small but out of the way. */
    struct { uint64_t base; uint64_t size; } mmaps[128];
    int           nmmaps;

    /* Per-process FPU/SSE state.  fxsave needs the buffer 16-byte aligned,
     * so the field carries that alignment and the whole struct inherits it. */
    uint8_t       fpu[512] __attribute__((aligned(16)));

    /*
     * The current directory, stored as a normalised absolute path rather than
     * as a pinned inode.  A path costs a string compare on every relative
     * lookup, but it makes getcwd() a memcpy and it cannot go stale when the
     * directory is renamed out from under us -- and on a read-mostly initrd
     * that trade is entirely in our favour.  Always begins with '/' and never
     * ends with one, except for the root itself.
     */
    char          cwd[GNUOS_PATH_MAX];

    /* File-creation mask.  We do not enforce permissions, but programs read
     * it back (umask(0) then umask(old) is a standard idiom), so it has to be
     * remembered per process and inherited across fork and exec. */
    uint32_t      umask;

    int           exit_status;
    int           term_sig;         /* non-zero if a signal killed us */
    int           stop_sig;         /* the signal that suspended us */
    int           reported;         /* stop already reported to the parent */

    char          name[16];
} proc_t;

/* Write the current process's TLS base into MSR FSBASE.  Called by the two
 * paths that return to user mode (ret_to_user and the syscall stub) so a
 * process always runs with its own thread-local storage. */
void proc_set_fs(proc_t *p);

/* ---- lifecycle -------------------------------------------------------- */
void    proc_init(void);
proc_t *proc_current(void);
proc_t *proc_by_pid(int pid);

/* Build PID 1 from an executable in the filesystem and make it runnable. */
int  proc_spawn_init(const char *path);

/* fork(): duplicate the caller.  Returns the child's pid to the parent and
 * 0 to the child, or a negative errno. */
int  proc_fork(regs_t *r);

/* execve(): replace the caller's image.  Only returns on failure. */
int  proc_execve(const char *path, char *const argv[], regs_t *r);

/* exit(): turn the caller into a zombie and schedule someone else. */
void proc_exit(int status) __attribute__((noreturn));

/* waitpid(): reap a child.  Blocks unless WNOHANG. */
int  proc_waitpid(int pid, int *status, int options);

/* ---- scheduling ------------------------------------------------------- */
void sched_start(void) __attribute__((noreturn));
void sched_yield(void);
void sched_tick(void);
void sched_block(wait_reason_t why);
/* Same, but the caller has already disabled interrupts and wants them left
 * that way -- the only race-free way for a driver to test "is there data?"
 * and go to sleep if there is not. */
void sched_block_irqoff(wait_reason_t why);
/* Block with a deadline, interrupts already off.  The sleeper is woken either
 * by whoever it is waiting for or by the timer after `ticks` ticks, whichever
 * comes first -- what a VTIME read needs so it can doze instead of spinning
 * (with nothing else runnable, a polling loop would burn a whole CPU). */
void sched_block_timeout(wait_reason_t why, uint64_t ticks);
void sched_wake(proc_t *p);
/* Wake everybody sleeping for the same reason (a driver got some data). */
void sched_wake_reason(wait_reason_t why);
/* Wake anyone whose deadline has passed.  Called from the timer interrupt. */
void sched_expire_timeouts(void);

/* ---- signals ---------------------------------------------------------- */
int  proc_signal(proc_t *p, int sig);
int  proc_signal_group(int pgid, int sig);
void proc_check_signals(regs_t *r);

/*
 * The pending signals that should break a process out of a blocking call.
 * SIGCHLD and SIGCONT are deliberately excluded: they arrive constantly
 * during normal job control, and a waitpid() that returned EINTR every time
 * one of its own children exited would never reap anything.
 */
uint64_t proc_pending_signals(const proc_t *p);

/*
 * True if `sig` would not actually stop or kill `p` right now, because the
 * process is ignoring it or has it blocked.  The terminal needs this: POSIX
 * says a background write that would raise SIGTTOU goes through unhindered
 * when the writer is ignoring or blocking the signal.  Without the exemption
 * a shell -- which ignores SIGTTOU precisely so it can hand the terminal back
 * and forth -- would deadlock against its own tty.
 */
int proc_signal_blocked(const proc_t *p, int sig);

#endif
